# Generated by Django 5.0.6 on 2024-06-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='user',
            field=models.CharField(default='me', max_length=100),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='long_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
