# Generated by Django 5.0.6 on 2024-06-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_link', '0002_shortlink_user_alter_shortlink_long_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
